// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: client/protos/ServerStream.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageClient interface {
	Send(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (*ReceiveMessage, error)
	SendServerStream(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (Message_SendServerStreamClient, error)
	SendClientStream(ctx context.Context, opts ...grpc.CallOption) (Message_SendClientStreamClient, error)
	SendClientServerStream(ctx context.Context, opts ...grpc.CallOption) (Message_SendClientServerStreamClient, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) Send(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (*ReceiveMessage, error) {
	out := new(ReceiveMessage)
	err := c.cc.Invoke(ctx, "/protos.Message/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SendServerStream(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (Message_SendServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[0], "/protos.Message/SendServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageSendServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Message_SendServerStreamClient interface {
	Recv() (*ReceiveMessage, error)
	grpc.ClientStream
}

type messageSendServerStreamClient struct {
	grpc.ClientStream
}

func (x *messageSendServerStreamClient) Recv() (*ReceiveMessage, error) {
	m := new(ReceiveMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageClient) SendClientStream(ctx context.Context, opts ...grpc.CallOption) (Message_SendClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[1], "/protos.Message/SendClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageSendClientStreamClient{stream}
	return x, nil
}

type Message_SendClientStreamClient interface {
	Send(*SendMessage) error
	CloseAndRecv() (*ReceiveMessage, error)
	grpc.ClientStream
}

type messageSendClientStreamClient struct {
	grpc.ClientStream
}

func (x *messageSendClientStreamClient) Send(m *SendMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageSendClientStreamClient) CloseAndRecv() (*ReceiveMessage, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReceiveMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageClient) SendClientServerStream(ctx context.Context, opts ...grpc.CallOption) (Message_SendClientServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[2], "/protos.Message/SendClientServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageSendClientServerStreamClient{stream}
	return x, nil
}

type Message_SendClientServerStreamClient interface {
	Send(*SendMessage) error
	Recv() (*ReceiveMessage, error)
	grpc.ClientStream
}

type messageSendClientServerStreamClient struct {
	grpc.ClientStream
}

func (x *messageSendClientServerStreamClient) Send(m *SendMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageSendClientServerStreamClient) Recv() (*ReceiveMessage, error) {
	m := new(ReceiveMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServer is the server API for Message service.
// All implementations must embed UnimplementedMessageServer
// for forward compatibility
type MessageServer interface {
	Send(context.Context, *SendMessage) (*ReceiveMessage, error)
	SendServerStream(*SendMessage, Message_SendServerStreamServer) error
	SendClientStream(Message_SendClientStreamServer) error
	SendClientServerStream(Message_SendClientServerStreamServer) error
	mustEmbedUnimplementedMessageServer()
}

// UnimplementedMessageServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (UnimplementedMessageServer) Send(context.Context, *SendMessage) (*ReceiveMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMessageServer) SendServerStream(*SendMessage, Message_SendServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendServerStream not implemented")
}
func (UnimplementedMessageServer) SendClientStream(Message_SendClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendClientStream not implemented")
}
func (UnimplementedMessageServer) SendClientServerStream(Message_SendClientServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendClientServerStream not implemented")
}
func (UnimplementedMessageServer) mustEmbedUnimplementedMessageServer() {}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Message/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Send(ctx, req.(*SendMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SendServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServer).SendServerStream(m, &messageSendServerStreamServer{stream})
}

type Message_SendServerStreamServer interface {
	Send(*ReceiveMessage) error
	grpc.ServerStream
}

type messageSendServerStreamServer struct {
	grpc.ServerStream
}

func (x *messageSendServerStreamServer) Send(m *ReceiveMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Message_SendClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServer).SendClientStream(&messageSendClientStreamServer{stream})
}

type Message_SendClientStreamServer interface {
	SendAndClose(*ReceiveMessage) error
	Recv() (*SendMessage, error)
	grpc.ServerStream
}

type messageSendClientStreamServer struct {
	grpc.ServerStream
}

func (x *messageSendClientStreamServer) SendAndClose(m *ReceiveMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageSendClientStreamServer) Recv() (*SendMessage, error) {
	m := new(SendMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Message_SendClientServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServer).SendClientServerStream(&messageSendClientServerStreamServer{stream})
}

type Message_SendClientServerStreamServer interface {
	Send(*ReceiveMessage) error
	Recv() (*SendMessage, error)
	grpc.ServerStream
}

type messageSendClientServerStreamServer struct {
	grpc.ServerStream
}

func (x *messageSendClientServerStreamServer) Send(m *ReceiveMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageSendClientServerStreamServer) Recv() (*SendMessage, error) {
	m := new(SendMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Message_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendServerStream",
			Handler:       _Message_SendServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendClientStream",
			Handler:       _Message_SendClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendClientServerStream",
			Handler:       _Message_SendClientServerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "client/protos/ServerStream.proto",
}
